import type { Metadata } from "next";
import { Inter } from "next/font/google";

// components
import "./globals.css";
import { childrenType } from "@/src/interface/common";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: childrenType) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-full bg-gray-100">{children}</div>
      </body>
    </html>
  );
}
